apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
spec:
  selector:
    matchLabels:
      app: watcher
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
        - name: watcher
          image: 339713114514.dkr.ecr.ap-northeast-2.amazonaws.com/supertone:1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watcher
rules:
  - apiGroups: ["", "events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
  - kind: ServiceAccount
    name: watcher
    namespace: default
roleRef:
  kind: ClusterRole
  name: watcher
  apiGroup: rbac.authorization.k8s.io
