apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: 339713114514.dkr.ecr.ap-northeast-2.amazonaws.com/supertone:latest
          ports:
            - containerPort: 80
